version: "2.3.3"
services:




  mysql-db:
    image: mysql:latest
    container_name: devops-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devops_project_db
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - network1
  
  spring:
    image: emnahammami/5twin4-g5-projet1:spring
    restart: always
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://devops-db:3306/stationSki?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
  
    depends_on:
      - mysql-db
    stdin_open: true
    tty: true
    networks:
      - network1 

volumes:
  db_data: {}
networks:
  network1:
    driver: bridge